### PR TITLE
Fix installation on MySQL 5.7 and phpBB 3.2.7 

### PR DESCRIPTION
**Pull request by Sam152**

### CODE REVIEW

**Comment by Sam152** [comment]
I'm not a phpBB expert, but the following changes were required to get the extension installing. MySQL complained that anything within a primary key could not be NULL, so non-null default values were required for those columns. 

Also, VARCHAR seemed like the wrong descriptor but I'm not sure.

**Comment by Sam152** [comment]
Hm, in the first request to the API after clicking 'nczone' I get:

> In aggregated query without GROUP BY, expression #8 of SELECT list contains nonaggregated column 'aoe.t.rating_change'; this is incompatible with sql_mode=only_full_group_by [1140]

I think maybe I need a different database version? Also are these constraints up to date in the composer file for phpBB version: `>=3.1.4,<3.2.0@dev`

**Comment by Sam152** [comment]
Hm, setting this globally helped render the nczone page:

`SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));`

**Comment by mcepok** [comment]
> I'm not a phpBB expert, but the following changes were required to get the extension installing. MySQL complained that anything within a primary key could not be NULL, so non-null default values were required for those columns.
> 
> Also, VARCHAR seemed like the wrong descriptor but I'm not sure.

Strange, I just tested it and get the same error on a environment the installation works without any issues before.

> Hm, setting this globally helped render the nczone page:
> 
> `SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));`

I don't have issues viewing the nC Zone page even without any further adjustments (except for the one made in this PR). I'm using MariaDB (10.1+) with default configuration in production and on my dev environment, but I wouldn't expect there to be a difference to MySQL.

**Pull request merged**
